### ISSUE TITLE
Instrument Model

### ISSUE THREAD

**Issue by ncbrown1** [scalableinternetservices/JamSesh#4]
There should be a model corresponding to the known instruments of the world. (many to many with users, meaning the user plays that instrument). This could require a pivot table so that there could be more information attached to the relationship, such as proficiency, time played, etc.

**Comment by ShayanPersonal** [comment]
Instrument model implemented and associated with the profile model with a has_many :through relationship (through the instrument_profile model, which holds attributes such as proficiency and time played)
