### ISSUE TITLE
As a signed in User, I can edit my profile info so that I can edit what information is stored about me.

### ISSUE THREAD

**Issue by jmangel** [scalableinternetservices/JamSesh#9]

**Comment by jmangel** [comment]
Location, instruments + proficiency (profile_instrument many-to-many pivot table), artists, genres, desired instruments

**Comment by ncbrown1** [comment]
Note: We will need to add First Name, Last Name, Phone Number (optional), Birthday (optional) to the user profile, since that data could be useful even though it is not provided in the default devise user.

**Comment by ShayanPersonal** [comment]
Currently only thing that's missing is adding proficiency with the instruments you choose.
